package ru.itmo.sofi.essence.instrument;

public enum InstrumentType {
    PH_METER,
    KITCHEN_SCALES,
    ELECTRONIC_SCALES,
    MENDELEEVS_SCALES,
    PHOTOCOLORIMETER_KFK_2,
    PHOTOCOLORIMETER_KFK_3,
    SPECTROPHOTOMETER,
    FUME_HOOD,
    WATER_BATH,
    SAND_BATH,
    ULTRASONIC_BATH,
    AUTOMATIC_PIPETTE_1,
    AUTOMATIC_PIPETTE_5,
    DRYING_OVEN,
    MAGNETIC_STIRRER,
    ELECTIC_STORE,
    STERILLIZER
}
